In [345]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [346]:
dataset = pd.read_csv('train.csv')

In [347]:
dataset['HomePlanet'].unique().tolist()

['Europa', 'Earth', 'Mars', nan]

In [348]:
dataset['Destination'].unique().tolist()

['TRAPPIST-1e', 'PSO J318.5-22', '55 Cancri e', nan]

In [349]:
dataset.replace({'HomePlanet':{'Europa':0,'Earth':1,'Mars':2}}, inplace=True)
dataset.replace({'Destination':{'TRAPPIST-1e':0,'PSO J318.5-22':1,'55 Cancri e':2}}, inplace=True)

In [350]:
dataset[['CryoSleep', 'VIP','Transported']] = (dataset[['CryoSleep', 'VIP','Transported']] == True).astype(int)
dataset.tail()

PassengerId  HomePlanet  CryoSleep     Cabin  Destination   Age  VIP  \
8688     9276_01         0.0          0    A/98/P          2.0  41.0    1   
8689     9278_01         1.0          1  G/1499/S          1.0  18.0    0   
8690     9279_01         1.0          0  G/1500/S          0.0  26.0    0   
8691     9280_01         0.0          0   E/608/S          2.0  32.0    0   
8692     9280_02         0.0          0   E/608/S          0.0  44.0    0   

      RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
8688          0.0     6819.0           0.0  1643.0    74.0  Gravior Noxnuther   
8689          0.0        0.0           0.0     0.0     0.0    Kurta Mondalley   
8690          0.0        0.0        1872.0     1.0     0.0       Fayey Connon   
8691          0.0     1049.0           0.0   353.0  3235.0   Celeon Hontichre   
8692        126.0     4688.0           0.0     0.0    12.0   Propsh Hontichre   

      Transported  
8688            0  
8689            0  
8690            1  
8691            0  
8692            1

In [351]:
#checking the missing values in each columns
dataset.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep         0
Cabin           199
Destination     182
Age             179
VIP               0
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

In [352]:
#repalcing the missing values in Age with mean value
dataset['Age'].fillna(dataset['Age'].mean(),inplace = True)

In [353]:
#finding the mode value of HomePlanet to replace NaN with that
print(dataset['HomePlanet'].mode())

0    1.0
Name: HomePlanet, dtype: float64


In [354]:
#repalcing the missing values in HomePlanet with mode value
dataset['HomePlanet'].fillna(dataset['HomePlanet'].mode()[0],inplace = True)

In [355]:
print(dataset['CryoSleep'].mode())

0    0
Name: CryoSleep, dtype: int32


In [356]:
dataset['CryoSleep'].fillna(dataset['CryoSleep'].mode()[0],inplace = True)

In [357]:
print(dataset['VIP'].mode())

0    0
Name: VIP, dtype: int32


In [358]:
dataset['VIP'].fillna(dataset['VIP'].mode()[0],inplace = True)

In [359]:
print(dataset['Destination'].mode())

0    0.0
Name: Destination, dtype: float64


In [360]:
dataset['Destination'].fillna(dataset['Destination'].mode()[0],inplace = True)

In [361]:
dataset['RoomService'].fillna(dataset['RoomService'].mean(),inplace = True)
dataset['FoodCourt'].fillna(dataset['FoodCourt'].mean(),inplace = True)
dataset['ShoppingMall'].fillna(dataset['ShoppingMall'].mean(),inplace = True)
dataset['Spa'].fillna(dataset['Spa'].mean(),inplace = True)
dataset['VRDeck'].fillna(dataset['VRDeck'].mean(),inplace = True)

In [362]:
dataset.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep         0
Cabin           199
Destination       0
Age               0
VIP               0
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name            200
Transported       0
dtype: int64

In [363]:
dataset.head()

PassengerId  HomePlanet  CryoSleep  Cabin  Destination   Age  VIP  \
0     0001_01         0.0          0  B/0/P          0.0  39.0    0   
1     0002_01         1.0          0  F/0/S          0.0  24.0    0   
2     0003_01         0.0          0  A/0/S          0.0  58.0    1   
3     0003_02         0.0          0  A/0/S          0.0  33.0    0   
4     0004_01         1.0          0  F/1/S          0.0  16.0    0   

   RoomService  FoodCourt  ShoppingMall     Spa  VRDeck               Name  \
0          0.0        0.0           0.0     0.0     0.0    Maham Ofracculy   
1        109.0        9.0          25.0   549.0    44.0       Juanna Vines   
2         43.0     3576.0           0.0  6715.0    49.0      Altark Susent   
3          0.0     1283.0         371.0  3329.0   193.0       Solam Susent   
4        303.0       70.0         151.0   565.0     2.0  Willy Santantines   

   Transported  
0            0  
1            1  
2            0  
3            0  
4            1

In [364]:
X = dataset.iloc[:,[1,2,4,5,6,7,8,9,10,11]].values
y = dataset.iloc[:,13].values

In [365]:
print(X)

[[0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 0.000e+00 0.000e+00 ... 2.500e+01 5.490e+02 4.400e+01]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 6.715e+03 4.900e+01]
 ...
 [1.000e+00 0.000e+00 0.000e+00 ... 1.872e+03 1.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 2.000e+00 ... 0.000e+00 3.530e+02 3.235e+03]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 1.200e+01]]


In [366]:
print(y)

[0 1 0 ... 1 0 1]


In [367]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [368]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler  #doing Standardization 
sc = StandardScaler()
x_train = sc.fit_transform(X_train)
x_test = sc.transform(X_test)

In [369]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 89, criterion = 'entropy', random_state=0)
classifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=89, random_state=0)

In [370]:
y_pred = classifier.predict(X_test)

In [371]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [372]:
#Accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print('Accuracy is %f'% accuracy)

Accuracy is 0.784729


In [373]:
#Precision
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred)
print('Precision is %f'% precision)

Precision is 0.779556


In [374]:
#Recall
from sklearn.metrics import recall_score
recall = recall_score(y_test, y_pred)
print('Recall is %f'% recall)

Recall is 0.799453


In [375]:
test_data = pd.read_csv('test.csv')

In [376]:
test_data['HomePlanet'].unique().tolist()

['Earth', 'Europa', 'Mars', nan]

In [377]:
test_data['Destination'].unique().tolist()

['TRAPPIST-1e', '55 Cancri e', 'PSO J318.5-22', nan]

In [378]:
test_data.replace({'HomePlanet':{'Europa':0,'Earth':1,'Mars':2}}, inplace=True)
test_data.replace({'Destination':{'TRAPPIST-1e':0,'PSO J318.5-22':1,'55 Cancri e':2}}, inplace=True)

In [379]:
test_data[['CryoSleep', 'VIP']] = (test_data[['CryoSleep', 'VIP']] == True).astype(int)
test_data.tail()

PassengerId  HomePlanet  CryoSleep     Cabin  Destination   Age  VIP  \
4272     9266_02         1.0          1  G/1496/S          0.0  34.0    0   
4273     9269_01         1.0          0       NaN          0.0  42.0    0   
4274     9271_01         2.0          1   D/296/P          2.0   NaN    0   
4275     9273_01         0.0          0   D/297/P          NaN   NaN    0   
4276     9277_01         1.0          1  G/1498/S          1.0  43.0    0   

      RoomService  FoodCourt  ShoppingMall   Spa  VRDeck              Name  
4272          0.0        0.0           0.0   0.0     0.0       Jeron Peter  
4273          0.0      847.0          17.0  10.0   144.0     Matty Scheron  
4274          0.0        0.0           0.0   0.0     0.0       Jayrin Pore  
4275          0.0     2680.0           0.0   0.0   523.0    Kitakan Conale  
4276          0.0        0.0           0.0   0.0     0.0  Lilace Leonzaley

In [380]:
test_data.isnull().sum()

PassengerId       0
HomePlanet       87
CryoSleep         0
Cabin           100
Destination      92
Age              91
VIP               0
RoomService      82
FoodCourt       106
ShoppingMall     98
Spa             101
VRDeck           80
Name             94
dtype: int64

In [381]:
#repalcing the missing values in Age with mean value
test_data['Age'].fillna(test_data['Age'].mean(),inplace = True)

In [382]:
#finding the mode value of HomePlanet to replace NaN with that
print(test_data['HomePlanet'].mode())

0    1.0
Name: HomePlanet, dtype: float64


In [383]:
#repalcing the missing values in HomePlanet with mode value
test_data['HomePlanet'].fillna(test_data['HomePlanet'].mode()[0],inplace = True)

In [384]:
print(test_data['CryoSleep'].mode())

0    0
Name: CryoSleep, dtype: int32


In [385]:
test_data['CryoSleep'].fillna(test_data['CryoSleep'].mode()[0],inplace = True)

In [386]:
print(test_data['VIP'].mode())

0    0
Name: VIP, dtype: int32


In [387]:
test_data['VIP'].fillna(test_data['VIP'].mode()[0],inplace = True)

In [388]:
print(test_data['Destination'].mode())

0    0.0
Name: Destination, dtype: float64


In [389]:
test_data['Destination'].fillna(test_data['Destination'].mode()[0],inplace = True)

In [390]:
test_data['RoomService'].fillna(test_data['RoomService'].mean(),inplace = True)
test_data['FoodCourt'].fillna(test_data['FoodCourt'].mean(),inplace = True)
test_data['ShoppingMall'].fillna(test_data['ShoppingMall'].mean(),inplace = True)
test_data['Spa'].fillna(test_data['Spa'].mean(),inplace = True)
test_data['VRDeck'].fillna(test_data['VRDeck'].mean(),inplace = True)

In [391]:
test_data.isnull().sum()

PassengerId       0
HomePlanet        0
CryoSleep         0
Cabin           100
Destination       0
Age               0
VIP               0
RoomService       0
FoodCourt         0
ShoppingMall      0
Spa               0
VRDeck            0
Name             94
dtype: int64

In [392]:
test = test_data.iloc[:,[1,2,4,5,6,7,8,9,10,11]].values

In [393]:
print(test)

[[1.000e+00 1.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 2.823e+03 0.000e+00]
 [0.000e+00 1.000e+00 2.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [2.000e+00 1.000e+00 2.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 5.230e+02]
 [1.000e+00 1.000e+00 1.000e+00 ... 0.000e+00 0.000e+00 0.000e+00]]


In [394]:
predictions = classifier.predict(test)

In [395]:
output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Transported': predictions})
output.to_csv('submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!
